language: python

sudo: false

cache:
  - pip

python:
 - "3.6"

addons:
 postgresql: "9.4"
 apt:
  packages:
   - "postgresql-9.4-postgis-2.3"

env:
 - DJANGO_VERSION=2.0.*
   db_name=calaccess_website
   db_user=postgres
   db_password=''
   rds_host=localhost

install:
 - pip install -r requirements.txt
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION

before_script:
  - psql -c 'create database calaccess_website;' -U postgres
  - fab setconfig:aws_access_key_id,''
  - fab setconfig:aws_secret_access_key,''
  - fab setconfig:aws_region_name,''
  - fab setconfig:key_name,''
  - fab setconfig:db_name,''
  - fab setconfig:db_user,''
  - fab setconfig:db_password,''
  - fab setconfig:s3_archived_data_bucket,''
  - fab setconfig:s3_baked_content_bucket,''
  - fab setconfig:email_user,''
  - fab setconfig:email_password,''
  - fab setconfig:rds_host,''

script:
  - make test

after_success:
 - coveralls
