language: python

sudo: false

cache:
  - pip

python:
 - "2.7"
 - "3.5"

env:
 - DJANGO_VERSION=1.9.7 db_name=calaccess_website db_user=postgres db_password='' rds_host=localhost
 - DJANGO_VERSION=1.10a1 db_name=calaccess_website db_user=postgres db_password='' rds_host=localhost

before_script:
  - psql -c 'create database calaccess_website;' -U postgres

install:
 - pip install -r requirements.txt
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION

script:
  - make test

after_success:
 - coveralls
