language: python

sudo: false

cache:
  - pip

python:
 - "2.7"

env:
 - DJANGO_VERSION=1.9.8 db_name=calaccess_website db_user=postgres db_password='' rds_host=localhost
 - DJANGO_VERSION=1.10rc1 db_name=calaccess_website db_user=postgres db_password='' rds_host=localhost

install:
 - pip install -r requirements.txt
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION

before_script:
  - psql -c 'create database calaccess_website;' -U postgres
  - printf '[DEV]\n aws_access_key_id = \n aws_secret_access_key = \n aws_region_name = \n key_name = \n db_name = \n db_user = \n db_password = \n s3_archived_data_bucket = \n s3_baked_content_bucket = \n email_user = \n email_password = \n rds_host = \n' > .env
  
script:
  - make test

after_success:
 - coveralls
