language: python

sudo: false

cache:
  - pip

python:
 - "2.7"
 - "3.5"

env:
 - DJANGO_VERSION=1.8.13
 - DJANGO_VERSION=1.9.7
 - DJANGO_VERSION=1.10a1

install:
 - pip install -r requirements.txt
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION

script:
  - make test

after_success:
 - coveralls

